language: cpp
sudo: false

linux64_addons:
    addons: &linux64
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - gcc-5
        - libboost-dev
        - libboost-filesystem1.54-dev
        - valgrind

env:

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons: *linux64
      env: COMPILER_C=gcc-5 COMPILER_CXX=g++-5
    - os: linux
      compiler: clang
      addons: *linux64
      env: COMPILER_C=clang COMPILER_CXX=clang++
    - os: linux
      compiler: gcc
      env: VALGRIND=ON
      addons: *linux64
    - os: linux
      compiler: gcc
      env: USE_ICC=ON
      addons: *linux64
    - os: linux
      compiler: gcc
      env: USE_PGI=ON
      addons: *linux64
    - os: linux
      env: EMSCRIPTEN=ON
      addons: *linux64
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: COMPILER_C=clang COMPILER_CXX=clang++
  allow_failures:
    - env: USE_ICC=ON
    - env: USE_PGI=ON

before_install:
  - cd $TRAVIS_BUILD_DIR
  - source ci/travis_setup.sh
  - $CC --version
  - $CXX --version

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - $CMAKE_CONFIGURE cmake .. $CMAKE_ARGS
  - make -j2
  - ctest -j2 --output-on-failure
